# Change these first
owner: nexusdiscord # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SubDL Subtitles
    url: https://subdl.strem.top
  - name: SubSource Subtitles
    url: https://subsource.strem.top

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.strem.top
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: strem.top
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
